name: Reflex App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install reflex
          pip install -r requirements.txt  # if you have additional requirements

      - name: Run tests
        run: |
          reflex init
          pytest tests/  # if you have tests

      - name: Start Reflex app (background process)
        run: |
          nohup reflex run > reflex.log 2>&1 &
          echo "Reflex app starting in background..."
          sleep 10  # Give it time to start
          cat reflex.log

      - name: Verify app is running
        run: |
          curl -s http://localhost:3000 | grep "Your App" || exit 1

      # Optional deployment steps (choose one)
      - name: Deploy to Reflex hosting (optional)
        if: github.ref == 'refs/heads/main'
        run: |
          reflex deploy --no-prompts
        env:
          REFLEX_TOKEN: ${{ secrets.REFLEX_TOKEN }}