name: Deploy to Vercel

on: workflow_dispatch

jobs:
  app:
    name: Setup Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Upgrade Pip
        run: python3 -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Export
        run: reflex export --no-zip
