name: Deploy to Vercel
on:
  push:
    branches: [main]  # Trigger on pushes to main branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build static frontend
        run: reflex export --frontend-only --no-zip
        env:
          API_URL: "${{ secrets.API_URL }}"  # Use GitHub Secrets for API_URL
      - name: Deploy to Vercel
        uses: nicholasgriffintn/github-branch-deployer-action@v1
        with:
          target_branch: vercel-deploy  # Branch Vercel monitors
          folder: .web/_static  # Reflex's static output directory
