on: workflow_dispatch

jobs:
  deps:
    name: Start Application
    runs-on: ubuntu-latest
    steps:
      - name: Add Repository
        uses: actions/checkout@v4
      - name: Start .venv
        run: |
          source .venv/bin/activate
      - name: Install Dependecies
        run: |
          pip install -r requirements.txt
      - name: Start Reflex
        run: |
          docker run -d -p 3000:3000 -p 8000:8000 --name app reflex-project:latest
          REFLEX_API_URL=0.0.0.0:8000 reflex export
