on: workflow_dispatch

jobs:
  deps:
    name: Start Application
    runs-on: ubuntu-latest
    steps:
      - name: Add Repository
        uses: actions/checkout@v4
      - name: Start .venv
        run: |
          source .venv/bin/activate
      - name: Install Dependecies
        run: |
          pip install -r requirements.txt
      - name: Start Reflex
        run: |
          API_KEY='https://nova-lemon-omega.vercel.app/' reflex export
