name: Deploy Reflex to Vercel

on: workflow_dispatch     # or any branch you're deploying from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install reflex fastapi uvicorn
          pip install -r requirements.txt

      - name: Export Frontend
        env:
          API_URL: https://nova-lemon-omega.vercel.app/api
        run: reflex export --frontend-only --no-zip

      - name: Export Backend
        run: reflex export --backend-only --no-zip

      - name: Upload for Vercel
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            .web/_static
            backend/
