on: workflow_dispatch

jobs:
  start:
    name: start reflex
    runs-on: ubuntu-22.04

    steps:
    - name: grep
      run: |
        grep 'import reflex as rx' -Ri /home/
    - name: Start
      run: |
        pip install nova/requirements.txt
        reflex run --env prod

