on:
  workflow_dispatch

jobs:
  start:
    name: deploy to staging
    runs-on: ubuntu-22.04

    steps:
    - name: grep
      run: |
        grep / -Ri 'import reflex as rx'
    - name: Start
      run: |
        pip install nova/requirnments.txt
        reflex run --env prod

