on: workflow_dispatch

jobs:
  start:
    name: Start Reflex
    runs-on: ubuntu-22.04

    steps:
    - name: Start
      run: |
        pip install nova/requirements.txt
        reflex run --env prod

