on: workflow_dispatch

jobs:
  start:
    name: Start Reflex
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start Reflex Server
        run: |
          source .venv/bin/activate
          pip install ./requirements.txt
          reflex run --env prod
